### ISSUE TITLE
preroute & preprocess not called when navigating views using tab bar

### ISSUE THREAD

**Issue by jvence** [nolimits4web/Framework7#1055]
I have created a tab-bar app and want to intercept when a user changes views using the tab bar button. Added the following to my app init but neither preroute or preprocess are ever called when a user presses a button on the tab to change views

```
var myApp = new Framework7({
    // If it is webapp, we can enable hash navigation:
    preroute: function (view, options) {
        console.log("preroute: " + view);
        return true; //required to prevent default router action
    },
    pushState: false,
    pushStateOnLoad:false,
    preprocess: function (content, url, next) {
        console.log("preprocess: " + url);
    }
});
```

**Comment by valnub** [comment]
Hi, sorry for the late reply, can you please post a jsfiddle or codepen example so we can reproduce this issue? Thanks.

You can use one of these templates for that:

- iOS [JSFiddle](https://jsfiddle.net/mvs820k0/)/[Codepen](https://codepen.io/nolimits4web/pen/vXmmgG)
- Material [JSFiddle](https://jsfiddle.net/u8a87yd2/2/)/[Codepen](https://codepen.io/nolimits4web/pen/pEPPPK)

**Comment by nolimits4web** [comment]
It is just switching tabs, router doesn't work here at all. You may need to use Tabs' show/hide events

**Comment by aminur** [comment]
Will this be changed so that tabs uses router?

In terms of loading data into Template7.data from an ajax request to server, if you want it all available, does Framework7 recommend a particular place to put that code?

At the moment I am calling a function to make my get request straight after 'new Framework7...' but before I manually run myApp.init();
