### ISSUE TITLE
Framework7 + VueJS (single page app without ajax page)

### ISSUE THREAD

**Issue by yezongyang** [nolimits4web/Framework7#1122]
Vue or Angular also has route for change page,
Create SPA with Mvvm(Vue, Angular, React) without framework7 route?

**Comment by yangconghou** [comment]
With the upstairs

**Comment by valnub** [comment]
I recommend to rely on F7 routing rather than use a different framework as it might mess up navigation. You're free to give it a try though :)
Posting your results would be very interesting as well.

You might want to read this: http://www.timo-ernst.net/blog/2016/03/04/use-angular-router-framework7/

I personally use Angular only for data binding, services and controller.

**Comment by valnub** [comment]
@yezongyang Does that make sense at all? Push state add the current state via hash tag to the url so it can only be applied to one view, I think.

**Comment by valnub** [comment]
@yezongyang Just found this quote from Vladi in an older issue:

> pushState works only for main View

So, I guess the answer is no :-)
