### ISSUE TITLE
Going back re-initialises the previous page

### ISSUE THREAD

**Issue by sinakarimi** [nolimits4web/Framework7#1128]
This is a (multiple allowed):
* [x] bug

* Framework7 Version: 1.4.2
* Platform and Target: IOS and Android

### What you did
When navigating from one page to another, in this case a category list to a detail page:
```
<!-- in category list -->
<a ng-href="detail.html" class="item-link item-content">
```
and then clicking back to the "category" page from the detail page:
```
<div class="left sliding"><a href="#category" class="back link"><i class="icon icon-back"></i><span>Back</span></a></div>
```
The category list is initialised again. Is there something I'm missing here?

**Comment by valnub** [comment]
Hi, can you show this issue in a fiddle? http://jsfiddle.net

**Comment by valnub** [comment]
Also, I noticed that you seem to use Angular because of `ng-href`. If you're creating your list via ng-repeat and data binding, then it's very likely that either your list model array gets refreshed (for some reason) or your controller gets re-initialized. Either way, it's more likely an Angular issue rather then Framework7 problem.

**Comment by sinakarimi** [comment]
Thanks @valnub - turns out it is an Angular issue. Will need to re-think the structure of the application to something that makes more sense. I'll close this for now until further notice.

**Comment by valnub** [comment]
No prob :)
Good luck
