### ISSUE TITLE
Audio playback integration solutions

### ISSUE THREAD

**Issue by Windancer** [nolimits4web/Framework7#1148]
https://github.com/kolber/audiojs

**Comment by J05HI** [comment]
Why to integrate that?

**Comment by valnub** [comment]
This can be solved very easily with few lines of code: http://stackoverflow.com/questions/10105063/how-to-play-a-notification-sound-on-websites/10107418#10107418

Since F7 is a UI framework I don't see why it should take care of audio. You should use a dedicated lib for that or use the code from the Stackoverflow link I posted.
