### ISSUE TITLE
Links stop working after going to two different pages

### ISSUE THREAD

**Issue by JosephShenton** [nolimits4web/Framework7#1151]
This is a (multiple allowed):
- [x] bug
- [ ] enhancement
- [ ] feature-discussion (RFC)
- Framework7 Version: 1.4.2
- Platform and Target: All
- Live Link or JSFiddle/Codepen: LocalHost
### What you did

Hi so when i click on the link to the users profile from the timeline then i click posts to view their posts then when i go all the way back to the timeline everything stops working on the timeline pages except for the tabs and in the other tabs everything is working so if you need to know the layout of the page changing it is this 
timeline->profile->posts 
But no matter what pages i go to the end result is the same and this happens on all tabs i was just doing the main one as the example. If you are wondering i am making a full featured social network that is why this is important!
### Expected Behavior

Everything still works
### Actual Behavior

Nothing workss but the tabs 

P.S. Remember, an issue is not the place to ask questions. You can use [Stack Overflow](http://stackoverflow.com/questions/tagged/framework7)
for that or join the #framework7 channel on irc.freenode.net, where we will be more
than happy to help answer your questions.

Before you open an issue, please check if a similar issue already exists or has been closed before.

**Comment by ZanderBrown** [comment]
you need to reinit the page

**Comment by iHackify** [comment]
how though?

**Comment by valnub** [comment]
Hi, we don't know your code and your description is very vague.

Can you please post a jsfiddle or codepen example so we can reproduce this issue? Thanks.

- http://www.jsfiddle.net
- http://www.codepen.io

Note: Please post your runnable example within 1 week, otherwise this issue will be closed.

**Comment by simonhochrein** [comment]
Same Problem

**Comment by iHackify** [comment]
@valnub hi it is kinda hard to upload it since it is php based

**Comment by valnub** [comment]
@iHackify I understand that but it's also very hard to debug without runnable code sample :-/

**Comment by valnub** [comment]
@iHackify You could also show us your application from your webserver where you host it. Or you post your code into a Github repo.

**Comment by nolimits4web** [comment]
@iHackify problem doesn't related to Ajax pages. You can check default Kitchen Sink demo which uses Ajax pages and there is everything fine, so double check layout of all pages is correct and your console errors. Otherwise would be good to see live example or something with the issue can be observed

**Comment by iHackify** [comment]
i will upload it now but it might take a while since it is 4.5 Gigabytes

**Comment by mindaboveall** [comment]
I think I might be able to shed some light on this issue.

if you enable template7 and are using precompiled templates when you go to a page that includes a template and hit back; template7 for some reason reloads the page that is sent to the right. This reload then errors out and crashes framework7 because the context is not successfully found resulting in a "ctx_1.example is undefined" TypeError.

The quick fix to this is to use {{#if this.example}} {{/if}} in your templating to check if the context exists before errors occur. This isn't an elegant solution and #1134 should be re-addressed since this should be handled programmatically.

The secondary issue us figuring out why template7 is reloading a page that is not in use in the first place.

Hope this helps!

**Comment by ZanderBrown** [comment]
Could you please expand you point?
Consider pointing code snippets here, on [Codepen](https://codepen.io) or on [JSFiddle](https://jsfiddle.net).
Make sure you have read the [documentation](http://framework7.io/docs/) correctly and followed any instructions it may give.

**Comment by ZanderBrown** [comment]
There hasn't been a response by the issues owner in 20 days.
This issue **will be closed in 7 days** if no further response is submitted
