### ISSUE TITLE
DOM7 $$.ajax deletes POST fields that are null.

### ISSUE THREAD

**Issue by ograva** [nolimits4web/Framework7#1159]
This is a (multiple allowed):
* [x] bug

* Framework7 Version: 1.4.2
* Platform and Target: IOS
* Live Link or JSFiddle/Codepen: 

### What you did

 I am submitting to a server process that requires all fields in the POST. I include the field called {barcode: ''} . I expect that it will send all the fields in sparams with the additional barcode and SKU fields in the data:sparams object .  Code is as follows

var sparams = {barcode:"",SKU:'',_search:'true',nd:'1475552290823',rows:'15', page:'1', sidx:'SKU',sord:'asc'};
	if(query.length == 18){
		sparams.barcode = query;
		sparams.SKU = "";
	}
	else{
		sparams.barcode = "";
		sparams.SKU = query;
	}
	console.log(sparams);

	$$.ajax({
		url:"http://"+IP_ADDRESS+"/Pos/JSON_InventorySearch", 
		method: "POST",
		data:sparams,
		processData: true,
		datatype: 'json',
		success: function (e,status,xhr) {...}
        });
}

### Actual Behavior

When the POST is sent to the url, not all the fields are  included when xhr.send(postData) is called

I modified framework7.js so I can log the Send XHR

            // Send XHR
	    console.log(postData);
            xhr.send(postData);  

console reports this sent after I type in 154 in the search query

SKU=154&_search=true&nd=1475552290823&rows=15&page=1&sidx=SKU&sord=asc

**Comment by valnub** [comment]
Hi, can you please post a jsfiddle or codepen example so we can reproduce this issue? Thanks.

You can use one of these templates for that:

- iOS [JSFiddle](https://jsfiddle.net/mvs820k0/)/[Codepen](https://codepen.io/nolimits4web/pen/vXmmgG)
- Material [JSFiddle](https://jsfiddle.net/u8a87yd2/2/)/[Codepen](https://codepen.io/nolimits4web/pen/pEPPPK)

Note: Please post your runnable example within 1 week, otherwise this issue will be closed.
