### ISSUE TITLE
WKWebView simple navigation problem

### ISSUE THREAD

**Issue by snsxn** [nolimits4web/Framework7#1160]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.4.2
* Platform and Target: Cordova iOS

### What you did
Added WKWebViewEngine to my Cordova App

### Expected Behavior
Navigation working fine

### Actual Behavior
Simple navigation is not working.
If I remove the plugin and use UIWebView there's no problem, but with WKWebView the internal links not working.
The current navigation I've used:
`<a href="somepage.html">Some page</a>`
While it works fine using UIWebView, with the new cordova-plugin-wkwebview-engine@1.1.0 is not working.

**Comment by snsxn** [comment]
Tried with a clean Cordova project with the contents of _dist_ folder from Framework7.
The links above _What about simple navigation_ are not working and no console errors.

**Comment by valnub** [comment]
Hi, what is wkwebview and what do you need an alternative engine?

**Comment by snsxn** [comment]
WkWebView is the current iOS engine to use with Cordova.

**Comment by valnub** [comment]
For me it looks like you're using ajax pages, right?

I don't think that works well with Cordova because index.html is served via file:/// protocol instead of http.

Ajax requires http though, it will not work with file:///

Try to create your app without ajax pages. In Cordova apps it's better to have all pages in one html file anyways because index.html is loaded almost instantly, so there is no reason to keep the file small.

If you want to split your pages each into an own file for better development structure, do that using mustache templates and strip that together using Gulp. The result is what should be compiled into index.html.

**Comment by snsxn** [comment]
Thanks @valnub.
For those who wants to know how to use inline pages in Framework7, this is the docs page: https://framework7.io/docs/pages-inline.html
