### ISSUE TITLE
About Swipeable Tabs

### ISSUE THREAD

**Issue by lixinchuang** [nolimits4web/Framework7#1189]
when I used Swipeable Tabs, I found a  mistake:

   If  one of the tabs's height value is too big, when i  changed to another  tab, the  tab will show  a  huge  blank area！

how can I resolve it！

**Comment by ZanderBrown** [comment]
I am unable to reproduce this issue http://framework7.io/docs-demos/tabs-swipeable.html

**Comment by Key7i** [comment]
I have same issue.

There is about same amount of text in all tabs in this example: http://framework7.io/docs-demos/tabs-swipeable.html That's why there is no difference. 

If there is a lot of of text in Tab1 and some text in Tab2. Then it will create a scroll and huge blank area on Tab2.. Also if you're at the bottom of Tab1 and swipe to Tab2. It will display bottom of Tab2 with blank area. Have to scroll up to see the actual content in Tab2.

Any solution for this?
