### ISSUE TITLE
Datepicker error when converting to local time

### ISSUE THREAD

**Issue by vousys** [nolimits4web/Framework7#1413]
Hi Guys, I've found a bug in inline Datepicker, using your kitchen example for android material.-
If you click on a day, it select another next to the one clicked.

**Comment by ZanderBrown** [comment]
Whats with the 'MDL' in the issue title?

Do you mean that two dates are selected or just the wrong one?

Could you provide a screencast or a jsFiddle/CodePen with steps to reproduce?

**Comment by vousys** [comment]
Hi! I 've download the kitchen-skin-material and upload it to  www.testeandoa.info/f7/kitchen-mdl/ Then I go to Calendar/Datepicker and then  use any of the calendars, but you can watch it with the big "Inline with custom toolbar" .
If I click on  march, 17 the one that stay selected is the 16. Allways mark with a circle, one day before to the one I select. I didn't add anything to the original code. ¿is a bug?

**Comment by GuillaumeBiton** [comment]
which device are you using because I can't reproduce your behavior.

**Comment by ZanderBrown** [comment]
Can't reproduce.

What's your device name & useragent string

**Comment by vousys** [comment]
I compile it with phonegap to create the app, and then test it in 2
different device: Ipad and MotoX Play

            [device_model] => iPad5,3
            [device_platform] => iOS
            [device_version] => 9.3.4

           [device_model] => XT1563
            [device_platform] => Android
            [device_version] => 6.0.1






[image: photo]

<http://facebook.com/vousys>  <http://us.linkedin.com/in/vosorio>
<http://twitter.com/vousys>  <http://instagram.com/vousys>
<http://behance.net/vousys>
Vero Osorio
Founder, VOUSYS
+54 911 4481 3751  <+54+911+4481+3751>*•* Skype: vousys
<#UNIQUE_ID_SafeHtmlFilter_UNIQUE_ID_SafeHtmlFilter_> *•*
 http://www.vousys.com  <http://www.vousys.com>*•* vosorio@vousys.com
<vosorio@vousys.com>*•*


2017-03-15 5:46 GMT-03:00 Guillaume Biton <notifications@github.com>:

**Comment by nolimits4web** [comment]
@vousys are you using latest 1.5.4 version?

**Comment by vousys** [comment]
Yes, the last one

**Comment by revertcreations** [comment]
I am also getting this, but I don't think it has anything to do with the Material Theme.

- Version 1.5.4

## What you did

Select a date from the default datepicker

## Expected Behavior

When you select the date, it should simply pick the one you clicked on.

## Actual Behavior

You can see in the gif below, that the chosen date is off by one. This is gif example is actually directly from the <a href="http://framework7.io/docs/calendar.html">framework7 docs</a>, however I am getting the same results building to ios/android/browser. 

## What I think caused it

The fix for issue <a href="https://github.com/nolimits4web/Framework7/commit/6fe777fb106048fe5d9be78c0311cbd3bf28d96c">#1385</a> is setting the p.value to a UTC timestamp. Since I am located in Mountain Time (specifically now MDT/UTC-6), the timestamp is sending the select day back one. 

` p.addValue(Date.UTC(dateYear, dateMonth, dateDay,0,0,0));`

So when selecting March 24, 2017, p.addValue is set to: 1490313600

1490313600 converts to Thursday March 23, 2017 18:00:00 (pm) in time zone America/Denver (MDT)

![framework7calpicker](https://cloud.githubusercontent.com/assets/17818973/24313979/e8027c5a-10a4-11e7-8966-e52d195f2f81.gif)

A side note, if you see when I try and click on the 21st, the click doesn't register. In the same bug report (<a href="https://github.com/nolimits4web/Framework7/issues/1385">#1385</a>) @valnub also brought this up. I have not looked too closely at this, but it usually happens the first time the calendar is launched and for the first few clicks. 

Thanks, and I hope I was thorough enough,

Trever

**Comment by ZanderBrown** [comment]
I had a feeling that fix might come back to haunt us.

**Comment by vousys** [comment]
Maybe. I'm Located in Argentina, UTC -3



[image: photo]

<http://facebook.com/vousys>  <http://us.linkedin.com/in/vosorio>
<http://twitter.com/vousys>  <http://instagram.com/vousys>
<http://behance.net/vousys>
Vero Osorio
Dev, VOUSYS
+54 911 4481 3751  <+54+911+4481+3751>*•* Skype: vousys
<#UNIQUE_ID_SafeHtmlFilter_UNIQUE_ID_SafeHtmlFilter_UNIQUE_ID_SafeHtmlFilter_>
 *•*
 http://www.vousys.com  <http://www.vousys.com>*•* vosorio@vousys.com
<vosorio@vousys.com>*•*


2017-03-24 18:40 GMT-03:00 Trever Hillis <notifications@github.com>:

**Comment by vousys** [comment]
Hi @nolimits4web can you update the file:  dist/js/framework7.min.js so I can download and use it? or should I have to wait for the next release? I saw you only updated the src/js/calendar.js

**Comment by ZanderBrown** [comment]
Wait till next release

**Comment by vousys** [comment]
When would it be? aproxim

**Comment by nolimits4web** [comment]
@vousys you can build it by yourself using Build instructions at https://github.com/nolimits4web/Framework7#build

**Comment by lenichols** [comment]
+1 im having this same issue with datepicker...

**Comment by Bluejay47** [comment]
+1 Same here.

**Comment by vousys** [comment]
Download the latest versión, it's fixed
