### ISSUE TITLE
Router.back with force:true

### ISSUE THREAD

**Issue by ChinLeung** [nolimits4web/Framework7#1495]
When you use the back of the router, even though it brings you to the right url, in the background, it's processing another page that it should not.

I have an event of `pageInit` which logs the page name that has been initialized.

Then if I navigate from `page1 -> page2 -> page3 -> page4` to go back to `page2`, the page2 will be shown properly but there will be a page1 init in the background.

I've tried to back in both Javascript and HTML:

## HTML

    <a href="page2.html" class="back" data-force="true">Back</a>

## Javascript

    mainView.router.back({'url': 'page2.html', 'force': true});

## Log

``` 
Init :: page 2
Init :: page 3
Init :: page 4
Init :: page 2
Init :: page 1
```

## Note

This only happens when I use the `Router.back`, everything works fine with `Router.load`. However, I want to use the back function for the reverse animation.

**Comment by ZanderBrown** [comment]
This is expected behaviour

**Comment by ChinLeung** [comment]
I thought that when you use the `Router.back` function with the `url` parameter, it's supposed to go back to the specified url. So why is it normal behaviour that it's going to the provided url, and doing a `back` in background?

**Comment by ZanderBrown** [comment]
yes because for swipe back to work the previous page must be in DOM.

F7 only keep 3 pages in DOM so Page 1 left the DOM when Page 4 was loaded.

`page:init` wasn't run for Page 2 when you went back to it because it was still in DOM from last time

However it was run for Page 1 because it was reentering the DOM and needs to be ready for swipeback to work

**Comment by ddtramp** [comment]
use $router. reloadPage(url)
