### ISSUE TITLE
TypeError: null is not an object (evaluating 'e.target.dom7EventData')

### ISSUE THREAD

**Issue by germancollado** [nolimits4web/Framework7#1636]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.6.4
* Platform and Target: Cordova / iOS

### What you did
Bring app from background to foreground

### Actual Behavior
Bringing app to foreground: TypeError: null is not an object (evaluating 'e.target.dom7EventData')

**Does not occur in version 1.6.0**

https://github.com/nolimits4web/Framework7/blob/master/src/js/dom7/dom7.js#L1034

**Comment by neogetz** [comment]
Same here, only available on IOS. On android for me the resume event works fine.

**Comment by kipelovets** [comment]
Same here. Any progress?

**Comment by chittattoo** [comment]
เมื่อ 10 มิ.ย. 2017 0:16 "Germán Collado Jara" <notifications@github.com>
เขียนว่า:

**Comment by elijnzaad** [comment]
This problem occurs in handleEvent on line 1048. It happens when the app has been switched to background and then to foreground again. This fires a "resume" event, which does not have a specific target, currentTarget or srcElement attached to it. As e.target is null in this case, the statement on line 1048 (v 1.6.4) fails.

If it really bothers you, you can apply a very dirty fix to the function at line 1047:
```    function handleEvent(e) {
      try {
        var eventData = e.target.dom7EventData || [];
        eventData.unshift(e);
        listener.apply(this, eventData);
      }
      catch(handleEventError) {
        // Just ignore
      }
    }
```
In my case this does the trick, but it is certainly not a permanent candidate.
By the way: thanks for your awesome framework! I really enjoy using it.

**Comment by puny-d** [comment]
hope fixed soon
