### ISSUE TITLE
Prevent 'JSON parse error' exceptions

### ISSUE THREAD

**Issue by petarov** [nolimits4web/Framework7#363]
The current implementation in *js/dom7-ajax.js* assumes that a server would always return a valid json to be parsed when the request completes. [This line](https://github.com/nolimits4web/Framework7/blob/master/src/js/dom7-ajax.js#L204), however, would break if that is not the case. For example, it would throw a [SyntaxError](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse#Exceptions), if the response is `200 OK` and there is no data, i.e., `responseData` is an empty string.

Now, I know this really is a problem of the faulty server (my faulty server in this case) and not the F7 lib, but I just wondered whether this should be handled more robustly. For example, at least check if `responseData` is an empty string and return `null` on `options.success`? An app can then make further verifications or present an error to the user.

**Comment by petarov** [comment]
:+1:  Works fine, error event is dispatched.

**Comment by felixarntz** [comment]
Is this actually resolved? When I look at the latest code, the fix is not in there.
The problem seems to be this commit: https://github.com/nolimits4web/Framework7/blob/6fe9a6864980af35898c633d780ca6281fcf8ed5/src/js/dom7-ajax.js

In the commit right before the one above, the fix is still there:
https://github.com/nolimits4web/Framework7/blob/daf8743773770ba8b401581bf29f0ae0f05c6495/src/js/dom7-ajax.js

Did it accidentally get lost by merging or something like that?

**Comment by nolimits4web** [comment]
@felixarntz seems to be you are looking in wrong place. It is fixed and it is still there, here is the latest version https://github.com/nolimits4web/Framework7/blob/master/src/js/dom7-ajax.js#L96

**Comment by nolimits4web** [comment]
Yes, it is fixed and still there https://github.com/nolimits4web/Framework7/blob/master/src/js/dom7-ajax.js#L207
