### ISSUE TITLE
make the pb pinch to zoom work in android

### ISSUE THREAD

**Issue by boynet** [nolimits4web/Framework7#385]
trying to help to solve it couldn't find the reason

2) is there a way to steal the zooming capabalities from photo browser to swiper?

**Comment by nolimits4web** [comment]
The problem is that Android doesn't have awesome "gesturestart/change/end" events which are in iOS. So yes, you can steal it from Photo Browser, which is by already realized on Swiper there, but it will not work on Android. If you need it on Android, you probably need to use Hammer.js which has custom cross-browser implementation of gestures
