### ISSUE TITLE
Framework7 is not fullscreen (minimal-ui) in safari on iphone

### ISSUE THREAD

**Issue by lihongxun945** [nolimits4web/Framework7#537]
because F7 set body to be height 100%, the tabbar and addressbar is not hide when scroll page

**Comment by nolimits4web** [comment]
It is true, but unfortunately there is no normal way to fix it

**Comment by lihongxun945** [comment]
It's really bad if I want to write a web page instead of a web app

**Comment by nolimits4web** [comment]
Sorry, i am not sure it is a good idea to change whole layout of app because of just this feature, which is not primary at all. And it will be not possible to scroll both `body` and `page` at the same time without loosing quality of UX. You can use something like this https://github.com/gajus/brim but it still leads to baad UX
