### ISSUE TITLE
use flexbox for layout of navbar, pages and toolbar

### ISSUE THREAD

**Issue by nimo23** [nolimits4web/Framework7#580]
Navbar and Toolbar uses css-position "absolute", navbar fixed to top, toolbar fixed to bottom. 

I guess, it would be really better to make the layout of navbar (header), "pages" and "toolbar" (footer) by using "flexbox-column-layout" where pages height is set to 100%. 

With such a layout, it would be really easy to adapt the height of navbar and toolbar to any size afterwards without breaking the other layout-content. 

As f7 uses different "layout types", flexbox-column-layout could also be adapt to these layout-styles. Using strict flexbox for layout-types enhances the flexibility to adapt styling changes and so on..

**Comment by nolimits4web** [comment]
It is but the problem is that navbar and toolbar should be above the page (like in native apps), they are not stacked on single layer. With such chosen layout you can make navbar/toolbar semitransparent (in iOS9 i'll add blurred background), and it can be dynamically hidden/shown. With flexbox layout where they all stack on single level it will be impossible

**Comment by nimo23** [comment]
Okay, thanks for the information!
