### ISSUE TITLE
Integration with major MV* Frameworks

### ISSUE THREAD

**Issue by SidneyS** [nolimits4web/Framework7#62]
Please make it pluggable, focus on its strenghts and integrate it with AngularJS and Cordova-iOS, document iPad functionality a bit better and you will see exploding user numbers. Right now, it is an (although very solid) island, because its UI paradigms cannot be easily decoupled from the business logic, e.g. in a databinding-based Angular app.

Cheers,
Sidney

P.S.: Thanks for your great work, your attention to detail in HTML5/CSS3 integration of native UI attributes is inspiring!

**Comment by psychonelo** [comment]
@DustinJSilk Have you managed to upload some examples? I am also struggling with Framework7 + Marionette.

**Comment by reelman** [comment]
+1

**Comment by DustinJSilk** [comment]
@psychonelo I havent my apologies. It wasn't easy getting it to all work together. Using both together seemed to cause various framework7 components to break down one after the other so it was a hack the whole way through the project. I'm not going down this route again but rather building my own animations and interactions with stand alone plugins and a raw backbone+marionette+require project. Hopefully sometime this framework will get updated to be compatible with other MVC frameworks.

**Comment by sandorTuranszky** [comment]
What is the status for MV* compatibility now?

**Comment by nolimits4web** [comment]
F7 is already compatible and can be used with many MVC frameworks, but not from the box. At least i see that many people using it with Angular and Meteor without problems. So i am closing this issue

**Comment by Under-Warz** [comment]
Hi guys,

I've made a bundle using Backbone - Marionette and Framework7 work together.

You can find the bundle with an exemple app here : https://github.com/Under-Warz/backbone-marionette-framework7

I've also made a Yeoman's Generator to create the app and the crossplatform part (with cordova) here : https://www.npmjs.com/package/generator-clintcross

It wasn't easy to make all things work together at start due to the Backbone's router and the Framework7's router but I made it.

Please give me your feedback and ask questions if needed :)
