### ISSUE TITLE
How to go back and refresh the previous page.

### ISSUE THREAD

**Issue by 631068264** [nolimits4web/Framework7#698]
For example :I want to go back to page1 from page2 and refresh page1
```
myApp.onPageBeforeAnimation('page1', function (page){

  if (page.from === 'left') {
       page.view.router.refreshPage();
  }
});
```
But page1 cant`t refresh .Why? @nolimits4web

**Comment by nolimits4web** [comment]
You can't do anything with router during it is animation, there is a "lock". You need to refresh your page first and then go back. Or do go back with `ignoreCache: true` and `force: true`

**Comment by 631068264** [comment]
**Refresh your page first and then go back** I have tried to use 
```
page.view.router.refreshPreviousPage()
```
and then use a go back function,But it can only refresh and it cant`t go back.Because it dont`t know when it refresh completely. And when the data is refreshing,it run go back. The real reason I don`t know.

So I want to go back first and then refresh.


I can`t understand your second suggest ,can you tell me more detailedly.
I use 
```
<a class="back" data-ignore-cache="true" data-force="true">back</a>
```
But it can`t work too. For example : 
My navigation is   Page1 -> Page2 -> Page3 
I want to go back to Page2, but when I use the code , it go back to Page1 from Page3.

Can you help me? @nolimits4web

**Comment by nolimits4web** [comment]
Then do it in after `pageAfterAnimation`

**Comment by 631068264** [comment]
Thanks.
The solution is 
```
page.view.router.back({
                    url: redirect,
                    force: true,
                    ignoreCache: true
                })
```

**Comment by nolimits4web** [comment]
Yes, this is what i meant in my first comment ;)

**Comment by noveweb** [comment]
But if previous page is a dynamic page like: mypage.html?id=01 and the url is unknow???

**Comment by hcw12889** [comment]
I have the same problem as **noveweb** mentioned.
Page1 is a page with xhr content loaded (In pageInit function)

When the page is navigating from page2 back to page1,
- using data-load-previous="true" with 'back' class does not reload the previous page
- by only using data-load-previous="true" does reload the previous page and the xhr content in the previous page but the page2 still exist on the screen
- data-force does reload the previous page but not including the xhr in it.
- adding pageReinit to page1 does not solve the problem.

And I tried the solution above in the topic, no luck.

Do you have any idea? @nolimits4web

**Comment by ionas** [comment]
I have got the same issue.
```

        page.view.router.back({
            url: 'users/index',
            force: true,
            ignoreCache: true
        });
```
works ... however I don't know the URL up front.

**Comment by obnijnil** [comment]
@ionas @noveweb 

To solve the dynamic previous url problem, I found the history entries can be read by
```
page.view.history
```
then, we can do something like
```
page.view.router.back({
  url: page.view.history[page.view.history.length - 2],
  force: true,
  ignoreCache: true
});
```

But I'm wondering why `page.view.router.refreshPreviousPage()` doesn't work in my code...

**Comment by yexing** [comment]
@hcw12889 
Look at the code in router.js line 838. The if part cause the problem you meet. I have commit it, but I have no idea about how to fix it.

**Comment by manware** [comment]
@obnijnil THANKS YOU MASTERRRRR!!!

**Comment by iamsudharshan** [comment]
Hi Vlad, @nolimits4web, can reload or refresh a piece of script on last back button.

**Comment by AndreRenaldo** [comment]
Hi i'm still new in f7, i have an index page which have login screen modal written on it too and also i have a function running in index onPageInit to load some information about user in a `<div id="info"></div>`, problem is when i do login i want to going back to new refreshed index page from wherever page i am before, i'm using all the solution you suggest, it do works, but my user information keep disappearing i assume it happens due to opening a new layer index page so the load function js on `<div id="info"></div> can run only once, this also affect the login alert, when i log out and log in again the alert that indicate login shows multiple times and it's buggers me
here is the code i use for log in and log out routing:

`mainView.router.refreshPage();
mainView.router.back({url: 'index.html', force: true, ignoreCache: true,reload: true});`

i change the div id info into class info so it solved but the alert still multiplies when i do login and log out several times, what i want to know is it possible to do log in in log in screen modal and then go to refreshed index page without opening some like new layer page so the alert problem's gone? @nolimits4web thanks before

**Comment by AndreRenaldo** [comment]
never mind i've just embedded login-screen into page and everything works smooth

**Comment by Santoshah** [comment]
I have 3 tabs in a news.html page. In each tab, there is news listing. When clicking on that news it goes its detail page. Even if I am in a third tab and go to detail page from there when returning back the first tab is selected. I want that 3rd tab selected if the detail page goes from 3rd tab.
It was working with 
`mainView.router.back({  ignoreCache: true});`

but when I updated to below code it stopped working. The page refresh but it goes to 1st tab at any case.
`mainView.router.back({url: 'news.html', force: true, ignoreCache: true,reload: true});`

Any idea?

**Comment by xiefangzhenz** [comment]
mark
