### ISSUE TITLE
Goto main index page and clear history

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [nolimits4web/Framework7#729]
Hello Framework team,

Is there a way to goto the main index page and clear the history?

Kind regards,
Mario

**Comment by nolimits4web** [comment]
Router's back method with `force:true`:
```
view.router.back({
  url: 'homeurl.html', // - in case you use Ajax pages
  pageName: 'homepage_name', // - in case you use Inline Pages or domCache
  force: true
});
```
Please use Forum for questions

**Comment by vousys** [comment]
@nolimits4web I had to create a function like this to go back to home after open 3 pages.

ex.:   Index -> page 1 -> page 2 -> page 3

On Page3 submit, I want to back to index.

```
        index_forzar_back : function () {

                    $$('.navbar-on-left').remove(); 
                    $$('.page-on-left').remove(); 

                    var index   = mainView.history[0];
                    var actual  = mainView.activePage.url;
                    mainView.history = [];
                    mainView.history.push(index);
                    mainView.history.push( actual );
                    mainView.router.back();

        },

```
But the problem is that each time I go back to Index, the callbacks  "onPageBeforeInit" and "onPageInit" are executed, and I think they shouldn't, because index is already loaded.

Maybe for future updates would be useful to have a function like "gobackindex" without reloading it (or optional), if this is posible. 
Thanks!

**Comment by ZanderBrown** [comment]
No it isn't loaded and this is expected behaviour for V1
