### ISSUE TITLE
animation use js

### ISSUE THREAD

**Issue by zhengnz** [nolimits4web/Framework7#806]
Framework7 is a really great framework, I very like it, but when I run it on android, the animation is very slow.
I saw the animation is based on css3, then I test an animation js tool - Velocity.js，I found it have high performance on mobile.
Can Velocity.js instead css3 animations in framework7?

**Comment by nolimits4web** [comment]
> then I test an animation js tool - Velocity.js

Did you test exact same animations with same styles in F7 on Android with CSS3 vs Velocity, or you just think so? :D I will check it, but i recommend you to use Crosswalk for Android

**Comment by octotree** [comment]
It is a well-known fact, that JS animations can have a much better performance (if done the proper way) than CSS animations. I was wondering too when I read that F7 uses CSS animations.

Nevertheless, F7 is a great framework, especially because it is able to integrate with other libraries. I use it with riot.js and after finding out how to use the routers together, it's just awesome.

**Comment by ZanderBrown** [comment]
I think the current CSS animations are perfectly smooth enough and @zhengnz never replied with any statistics
